### PR TITLE
Added Medusa App

### PR DESCRIPTION
**Pull request by TephlonDude**
Added Medusa App

### CODE REVIEW

**Comment by TephlonDude** [comment]
Not sure why the YAML under Lucky app failed as I did not make any changes to this file. The only changes that I made were to create the Medusa folder under the Apps folder and then create the appropriate files.

**Comment by Cp0204** [comment]
> Not sure why the YAML under Lucky app failed as I did not make any changes to this file. The only changes that I made were to create the Medusa folder under the Apps folder and then create the appropriate files.

https://github.com/IceWhaleTech/CasaOS-AppStore/commit/6effd055196690079509cc20ee9539342cb021dc

The problem has been fixed and you can try to submit again

**Comment by Cp0204** [comment]
If you can, please refer to the store cases and documents to improve more application information

**Comment by raller1028** [comment]
@TephlonDude Sorry for taking so long to reply to you, docker-compose.yml can be imported normally, also can be used normally. But docker-compose.yml some files in the mapping path I will help you to change to /DATA/AppData/$AppID/xxxx, and some images of the path will be in accordance with the official requirements of the path to change, thanks for your pull request!

**Pull request merged**
