### PR TITLE
[New App] MySpeed

### PR DESCRIPTION
**Pull request by joaobosconff**
Request #314

### CODE REVIEW

**Comment by raller1028** [comment]
image
Is this normal?

**Comment by joaobosconff** [comment]
> image Is this normal?

is not, i tested using custom app on CasaOS importing the docker compose, and worked perfectly.

**Comment by joaobosconff** [comment]
Tested on amd64 and arm, both worked, maybe is something on your network

**Comment by raller1028** [comment]
image
It's been playing all night. It's working well.

**Pull request merged**
