### PR TITLE
app: add FlareSolverr

### PR DESCRIPTION
**Pull request by calganaygun**
In this PR;
 - [FlareSolverr](https://github.com/FlareSolverr/FlareSolverr) added.
 It is some kind of a proxy app for HTTP requests. Some of Prowlarr's indexers require that solver to bypass CloudFlare.

How to test:
1. Install FlareSolver app.
2. Test with curl:
```bash
curl -L -X POST 'http://localhost:8191/v1' \
-H 'Content-Type: application/json' \
--data-raw '{
  "cmd": "request.get",
  "url": "https://prowlarr.servarr.com/v1/ping",
  "maxTimeout": 60000
}'
```
* Do not forget to change your hostname.
3. If you get a response, it is working :)
Output of curl

Or, directly test with Prowlarr: https://trash-guides.info/Prowlarr/prowlarr-setup-flaresolverr/#add-flaresolverr-to-prowlarr

### CODE REVIEW

**Comment by calganaygun** [comment]
Hello @CorrectRoadH 

Would you be able to take a look at this PR? I added testing instructions to make it easy to test for you :) I think many prowlerr users dependant on this app too :)

**Comment by CorrectRoadH** [comment]
> Hello @CorrectRoadH
> 
> Would you be able to take a look at this PR? I added testing instructions to make it easy to test for you :) I think many prowlerr users dependant on this app too :)

Yes, I am willing to handle this PR, but I am quite busy recently. I will test the application when I am free and merge it if it passes. It may take a day or two later.🥺

**Comment by calganaygun** [comment]
@CorrectRoadH I hope you doing well! Will you be able to take a look at this PR soon?

**Comment by CorrectRoadH** [comment]
Thanks for your contribution!❤️

**Pull request merged**
