### PR TITLE
Add FreshRSS to App Store

### PR DESCRIPTION
**Pull request by Minionguyjpro**
This adds FreshRSS to the app store for CasaOS. This also completes https://github.com/IceWhaleTech/CasaOS/issues/562 since it adds an RSS feed reader.

### CODE REVIEW

**Comment by CorrectRoadH** [comment]
image
it require username and password

**Comment by Minionguyjpro** [comment]
> image
> it require username and password
> 

Weird, it should open the web UI to do the setup instead. Will check later...

**Comment by Minionguyjpro** [comment]
Just tested my latest Docker Compose file. Seems to work fine for me. The setup loads for me after having created the container using the latest Docker Compose file from the latest commit I made. Are you sure that there isn't something conflicting there?

**Comment by Minionguyjpro** [comment]
Those last two commits (or well the last one, the first one had a mistake in it) have fixed the proper volumes to point to the local AppData folder, which it should (with a freshrss subdirectory with then the other two directories for the volume in it). And it works fine...

**Comment by CorrectRoadH** [comment]
LGTM! Thanks for you contribution.😃

**Pull request merged**
