### PR TITLE
add: rdt-client

### PR DESCRIPTION
**Pull request by calganaygun**
Adds [rogerfar/rdt-client](https://github.com/rogerfar/rdt-client)

### CODE REVIEW

**Comment by calganaygun** [comment]
I think the blocking GH Action needs to be re-run. @CorrectRoadH Is it possible for you to check again?

**Comment by Panchajanya1999** [comment]
hey @CorrectRoadH is it possible for you to look into it and add it asap? thank you!

**Comment by CorrectRoadH** [comment]
> hey @CorrectRoadH is it possible for you to look into it and add it asap? thank you!

Yes! I will to test the application and merge as soon as possible! 🙈 If I get any problem in the docker compose yaml, I will fix directly.

**Comment by CorrectRoadH** [comment]
> hey @CorrectRoadH is it possible for you to look into it and add it asap? thank you!

I got "Permission denied". Is the application is a not free app? I need pay for work?🤔
CleanShot 2024-06-07 at 22 38 40@2x

**Comment by CorrectRoadH** [comment]
> hey @CorrectRoadH is it possible for you to look into it and add it asap? thank you!

I

> > hey @CorrectRoadH is it possible for you to look into it and add it asap? thank you!
> 
> I got "Permission denied". Is the application is a not free app? I need pay for work?🤔 CleanShot 2024-06-07 at 22 38 40@2x

I just want to test whether the app works and what the quality is. We will not reject a good commercial app. just like plex.

**Comment by calganaygun** [comment]
Hello @CorrectRoadH , this is a download client for Debrid websites, which requires a subscription to debrid sites to use their services. For example, you need [Real-Debrid premium](https://real-debrid.com/premium) is required in order to use as a Real Debrid client. Also, implements a fake qBittorrent API interface to use with services support qBittorrent (Radarr, Sonarr etc.)

Real Debrid premium starts from 3 EUR, If needed I can also provide my API key to you for test purposes.

**Comment by CorrectRoadH** [comment]
> Hello @CorrectRoadH , this is a download client for Debrid websites, which requires a subscription to debrid sites to use their services. For example, you need [Real-Debrid premium](https://real-debrid.com/premium) is required in order to use as a Real Debrid client. Also, implements a fake qBittorrent API interface to use with services support qBittorrent (Radarr, Sonarr etc.)
> 
> Real Debrid premium starts from 3 EUR, If needed I can also provide my API key to you for test purposes.

If 

> Hello @CorrectRoadH , this is a download client for Debrid websites, which requires a subscription to debrid sites to use their services. For example, you need [Real-Debrid premium](https://real-debrid.com/premium) is required in order to use as a Real Debrid client. Also, implements a fake qBittorrent API interface to use with services support qBittorrent (Radarr, Sonarr etc.)
> 
> Real Debrid premium starts from 3 EUR, If needed I can also provide my API key to you for test purposes.

Thanks. you can send the api key to my email "a778917369@gmail.com" just for test the function. I don't have a Credit Cards to pay. 😂

**Comment by calganaygun** [comment]
@CorrectRoadH Did you have time to try it? I shared the key with you yesterday. If you can't find a torrent, you can try f[ree torrents.](https://webtorrent.io/free-torrents)

**Comment by CorrectRoadH** [comment]
> @CorrectRoadH Did you have time to try it? I shared the key with you yesterday. If you can't find a torrent, you can try f[ree torrents.](https://webtorrent.io/free-torrents)

Yes. But it didn't work for me.😂 I am finding the correct way to use it.
CleanShot 2024-06-08 at 20 39 25@2x

**Comment by Panchajanya1999** [comment]
> > @CorrectRoadH Did you have time to try it? I shared the key with you yesterday. If you can't find a torrent, you can try f[ree torrents.](https://webtorrent.io/free-torrents)
> 
> Yes. But it didn't work for me.😂 I am finding the correct way to use it. CleanShot 2024-06-08 at 20 39 25@2x

Working perfectly here. 
image

**Comment by CorrectRoadH** [comment]
> > > @CorrectRoadH Did you have time to try it? I shared the key with you yesterday. If you can't find a torrent, you can try f[ree torrents.](https://webtorrent.io/free-torrents)
> > 
> > 
> > Yes. But it didn't work for me.😂 I am finding the correct way to use it. CleanShot 2024-06-08 at 20 39 25@2x
> 
> Working perfectly here. image

OK, Thanks for your contribution. you can reset the api key. I download a torrent success. I will merge the PR right now.

**Comment by Panchajanya1999** [comment]
Thank you!!

**Comment by Panchajanya1999** [comment]
Hey @calganaygun i am using rdt-client for the past few days and I am facing memory related issues with rdt. It's like I am experiencing memory leaks, the memory keeps filling along with the swap if it runs for a longer time, especially when downloading larger files. 
Do you face the same too?

**Comment by calganaygun** [comment]
> Hey @calganaygun i am using rdt-client for the past few days and I am facing memory related issues with rdt. It's like I am experiencing memory leaks, the memory keeps filling along with the swap if it runs for a longer time, especially when downloading larger files. 
> Do you face the same too?

Hey @Panchajanya1999 no, I haven't experienced it. But it is likely to be about its internal downloader. Maybe you can try an external downloader which rdt client supports.

If this issue persist, you can directly ask about it in the rdt-client community/issues of GH repo because this casa os app directly uses official image of it. And they are gonna know much better about the rdt-client itself better than me :)

**Pull request merged**
