### PR TITLE
fix: Stremio

### LINKED ISSUE #361: Issue in stremio App in AppStore [#264]
Issue: Server error
Faild to Fetch Video

image
image

### PR DESCRIPTION
**Pull request by joaobosconff**
Closes #361

i found a docker-image version of @tsaridas and worked perfectly, fixes the failed to fetch error in some devices

### CODE REVIEW

**Comment by CorrectRoadH** [comment]
@raller1028 is the application in the PR work fine?

**Comment by CorrectRoadH** [comment]
Thank you for your contribution😃

**Comment by arunavo4** [comment]
Hey i Dont understand why the streamio service itself is not as a docker contaner ?

**Comment by joaobosconff** [comment]
> **[arunavo4](/arunavo4) ** commented

this docker image is the UI and Server combined.

**Comment by joaobosconff** [comment]
this docker image is the UI and Server combined.

**Pull request merged**
