### PR TITLE
add support for wallabag (arch:arm)

### PR DESCRIPTION
**Pull request by meauxt**
# Add Wallabag to the Appstore:
### Changes
this uses the `ugeek/wallabag:arm` image that has been built for raspberry pi. so will only work with **ARM** arch

#### Volumes:
This docker-compose will create two volumes
-  **data** SQLite 
- **images** Assets/Images

## related issue/request
#48

### CODE REVIEW

**Comment by raller1028** [comment]
Sorry, can you provide me with a screenshot of the yml file successfully imported (wallabag's webui), I've tried docker-compose and app json to import it, but neither opened successfully.

**Comment by meauxt** [comment]
@raller1028  here is the screenshot from my CasaOS showing the configuration I have 
image
image
image

I exported the the app using the export functionality in the UI and here is the JSON I got 
> {"host":"walla.home","protocol":"http","port_map":"80","cpu_shares":10,"restart":"unless-stopped","label":"wallabag","position":false,"index":"","icon":"https://icon.casaos.io/main/all/wallabag.png","network_model":"bridge","image":"ugeek/wallabag:arm","description":"","origin":"custom","ports":[{"container":"80","host":"8001","protocol":"tcp","desc":"","type":0}],"volumes":[{"container":"/var/www/wallabag/web/assets/images","host":"/DATA/AppData/Wallabag/images","type":0,"desc":""},{"container":"/var/www/wallabag/data","host":"/DATA/AppData/Wallabag/data","type":0,"desc":""}],"envs":[{"container":"SYMFONY__ENV__DOMAIN_NAME","host":"http://walla.home","desc":"","type":0}],"devices":[],"cap_add":[],"cmd":["wallabag"],"privileged":false,"host_name":"wallabag","container_name":"wallabag","appstore_id":0,"custom_id":"55a50e2f-d2e5-4759-be41-a2dac9f5cb0a","enable_upnp":false,"version":"1.0"}

Anything I am missing to include in the PR?  what can you share the error you are getting when importing the app
image

**Comment by raller1028** [comment]
@meauxt Sorry, I tried to use your json and install it on an arm64 but it still doesn't work
image

```
root@raspberrypi:~# docker ps
CONTAINER ID   IMAGE                COMMAND                  CREATED       STATUS         PORTS                                   NAMES
39d1b3b4a9e0   ugeek/wallabag:arm   "/entrypoint.sh wall…"   2 hours ago   Up 9 seconds   0.0.0.0:8001->80/tcp, :::8001->80/tcp   wallabag
root@raspberrypi:~# docker logs 39d
Starting provisioner...
 [WARNING]: Found both group and host with same name: localhost
Provisioner finished.
Starting provisioner...
 [WARNING]: Found both group and host with same name: localhost
root@raspberrypi:~# 
```

**Comment by meauxt** [comment]
@raller1028 sorry for the delayed reply. i will try it on new system and see what i get. will open the PR once i figure out what going on ¯\_(ツ)_/¯

**Comment by meauxt** [comment]
@raller1028 I just saw the logs you have and seem provision completed,are you unable to access it at port 8001 ? 
I think i need to update default value of the web UI currently set to my local DNS rewrite address `walla.home`

**Pull request closed without merging**
