### PR TITLE
new app: Alby Hub

### PR DESCRIPTION
**Pull request by calganaygun**
A new app Alby Hub added. A simple, straight-forward lightning node. 

Docker deployment specified at the official repo: https://github.com/getAlby/hub?tab=readme-ov-file#docker

Also 1to1 with example official docker-compose https://github.com/getAlby/hub/blob/master/docker-compose.yml

### CODE REVIEW

**Comment by calganaygun** [comment]
@CorrectRoadH I think you are the most active in the maintainers. The failed check looks like not related to this app. Can you confirm, and review the new app to merge into the official repository? Any issues and version bumps can be tracked by me if needed. Have a great sunday!

**Comment by MoritzKa** [comment]
Would love to see Alby Hub on CasaOS!

**Comment by CorrectRoadH** [comment]
Thanks for your contribution.

**Comment by itstomekk** [comment]
image
it's there!

**Comment by itstomekk** [comment]
@calganaygun how can we maybe update the description?

To: "A simple Bitcoin Lightning node with wallet, subaccounts and NWC connections"

image

**Pull request merged**
