### PR TITLE
[New APP] Twingate Connector

### PR DESCRIPTION
**Pull request by shubhankartrivedi**
This app will allow users to start a twingate connector.
For more info: https://www.twingate.com

### CODE REVIEW

**Comment by raller1028** [comment]
@shubhankartrivedi I import docker-compose.yml via customization
, it doesn't start properly (keeps restarting), can you help check what's wrong with docker-compose.yml?
image

**Comment by shubhankartrivedi** [comment]
Just see what it says. "TWINGATE_ACCESS_TOKEN is empty". 
You need a token from twingate.com to start the docker.

**Comment by raller1028** [comment]
@shubhankartrivedi I added the access_token, but the logs report an error saying that the refresh_token is missing, do I still need to download the client to get the refresh_token?Can you provide me with the token for me to test the app?
image
image

**Comment by shubhankartrivedi** [comment]
> @shubhankartrivedi I added the access_token, but the logs report an error saying that the refresh_token is missing, do I still need to download the client to get the refresh_token?Can you provide me with the token for me to test the app? image image

You need to go to twingate.com and then register your account and do all the steps. It will give you all the tokens to add as ENVs. Then it will work. 
Those are not something you need to create, those are tokens which are created by twingate on your account's dashboard.
I think you should check youtube on how to setup twingate account.
Else everything is working great.
Let me know how it goes.

**Comment by raller1028** [comment]
image
image
I followed the youtube tutorial, can you help me to see if it's ok for me to deploy it like this?

**Comment by shubhankartrivedi** [comment]
> image
> 
> image
> 
> I followed the youtube tutorial, can you help me to see if it's ok for me to deploy it like this?

Yes this is good.

**Pull request merged**
