### PR TITLE
[New Apps] Add MongoDB, Petio & Cloudflared

### PR DESCRIPTION
**Pull request by WisdomSky**
**Petio** 
Description: Petio is similar to [Ombi](https://github.com/IceWhaleTech/CasaOS-AppStore/tree/main/Apps/Ombi), but has much nicer UI.
Homepage: https://petio.tv/

**Cloudflared (with UI)**
Description: This cloudflared image comes with a WebUI where the user can set the tunnel token and start/stop the tunnel.
Homepage: https://hub.docker.com/r/wisdomsky/casaos-cloudflared

**MongoDB**
Homepage: https://hub.docker.com/_/mongo
> Note: Mongo is included since Petio uses MongoDB. So if the user has no existing MongoDB instance running on his machine, he/she can install the MongoDB app.

### CODE REVIEW

**Comment by tigerinus** [comment]
Awesome apps @WisdomSky 

@raller1028 please review and test as early as you can. Thank you!

**Comment by raller1028** [comment]
@WisdomSky Could you please update the dimensions of the screenshots inside? Screenshot image should be 1280x720 pixels and can be saved in either PNG or JPG format. Please try to keep the file size as small as possible.

**Comment by raller1028** [comment]
1. The parameter ports published requires a string type and will be fixed in the next release. At the moment we can only write published like this:  `published: "14333"`

2. MongoDB 5.0+ requires a CPU with AVX support, ZimaBoard use the N3450 cpu, which does not support AVX.
image

**Comment by WisdomSky** [comment]
> @WisdomSky Could you please update the dimensions of the screenshots inside? Screenshot image should be 1280x720 pixels and can be saved in either PNG or JPG format. Please try to keep the file size as small as possible.

Sure I will update it later. thanks.

> MongoDB 5.0+ requires a CPU with AVX support, ZimaBoard use the N3450 cpu, which does not support AVX. Docker log as follow:
I'm running CasaOS not on a ZimaBoard so I wasn't really been able to consider it. I will try mongo 4a and see if petio works fine with it.

**Comment by tigerinus** [comment]
Maybe two apps, MongoDB4 in future, and just MongoDB5 for now?

Just include a message in the `description` or `tips.pre_install` claiminf AVX is required?

**Comment by WisdomSky** [comment]
Changes applied.

- The Petio app now internally comes with MongoDB 4.4.2
- MongoDB app retains as 6.0.6
- Screenshots for Cloudflared and Petio Resized into max height of 1280px

**Comment by WisdomSky** [comment]
Standalone version of MongoDB v4 is added in #179.

**Pull request merged**
