### PR TITLE
[New App] Crafty Controller

### PR DESCRIPTION
**Pull request by charagender**
Created and tested Crafty Controller app for CasaOS as per requested in https://github.com/IceWhaleTech/CasaOS-AppStore/issues/64

Crafty Controller is an open source Minecraft Server Control Panel made with the objective of making the management of Minecraft Servers easy.

Thoroughly tested in production and confirmed working.

image

### CODE REVIEW

**Comment by raller1028** [comment]
@charagender 
I'm sorry to inform you, as a fellow Minecraft enthusiast, that there are currently two issues with this app :(
## The first is that the container name needs to be changed from crafty_container to crafty-container.
image


## The second problem is that I can't get into the admin page after installing it, but I can see the log is fine, can you help me to see what the problem is?
image
image

**Comment by charagender** [comment]
@raller1028 
> The first is that the container name needs to be changed from crafty_container to crafty-container.

Oh! Completely forgot to change that, thanks for pointing that out, will fix that later

> The second problem is that I can't get into the admin page after installing it, but I can see the log is fine, can you help me to see what the problem is?

That's strange, I never encountered that error, though I do see you're using port 8110 for the web UI, as stated to be in the docker compose file, while I'm using port 8111 in my screenshots (will also fix the `port_map` value!). Can you confirm that the error still occurs when using port 8111?

**Comment by raller1028** [comment]
@charagender 
Modify to https and use port 8111 for successful access!!!!
image
image

**Comment by charagender** [comment]
@raller1028 Thanks for confirming the fix worked! I've just committed the fix and added the before_install tips. I'd made them, but forgot to add them to the actual yaml file. Oops!

**Pull request merged**
