### PR TITLE
Update Home Assistant to the latest version

### LINKED ISSUE #471: [Bug] Update Home Assistant
## Problem
Home Assistant version in app store is very old as it used an outdated docker image and kinda doesn't work with some devices like (Tuya).
```
Current:
Docker Image: linuxserver/homeassistant
Version: 2023.11.3
```

## Solution
We need to update the docker image of Home Assistant to the latest address and version
```
New:
Docker Image: ghcr.io/home-assistant/home-assistant
Version: stable
```

I tried using `install a customized app` option but looks like that doesn't allow containers from outside app store database

### PR DESCRIPTION
**Pull request by itzzritik**
Update Home Assistant to the latest version and image location

```
New:
Docker Image: homeassistant/home-assistant
Version: 2024.5
```

Closes #471
Closes IceWhaleTech/CasaOS#1814

### CODE REVIEW

**Comment by itzzritik** [comment]
@CorrectRoadH 
Looks like validation, but not for HomeAssistant.

Can you please suggest, what went wrong?

**Comment by CorrectRoadH** [comment]
> @CorrectRoadH Looks like validation, but not for HomeAssistant.
> 
> Can you please suggest, what went wrong?

We prefer a fixed tags. `linuxserver/homeassistant:2023.11.3` not `stable` and `latest`. The former makes it easy to check if updates are available. The latter requires more inspection.🤔

**Comment by itzzritik** [comment]
@CorrectRoadH ThankYou for precise feedback, Let me fix it soon

**Comment by itzzritik** [comment]
@CorrectRoadH Can we trigger workflow again?

**Comment by CorrectRoadH** [comment]
Thanks for your contribution!

**Pull request merged**
